import streamlit as st
import pandas as pd
import pydeck as pdk
import json

# --- SECRETS & CONFIG ---
# This pulls from the 'Advanced Settings' in Streamlit Cloud
MAPBOX_TOKEN = st.secrets["MAPBOX_TOKEN"]

st.set_page_config(layout="wide", page_title="Unified Site Operations Center")

# Load the data generated by the update script
try:
    with open('latest_report.json') as f:
        data = json.load(f)
except:
    st.error("No data found. Please trigger the GitHub Action.")
    st.stop()

# --- HEADER METRICS ---
st.title(f"Operations Dashboard: {data['site_info']['name']}")
c1, c2, c3 = st.columns(3)
c1.metric("Soil Saturation", data['soil_moisture']['level'], data['soil_moisture']['status'])
c2.metric("Rainfall (USGS Archdale)", f"{data['weather_metrics']['observed_24h_precip']} in")
c3.metric("Concrete Status", data['concrete_ops']['pour_status'], f"Evap: {data['concrete_ops']['evap_rate']}")

# --- LABELED ACTION MAP ---
st.subheader("Field Maintenance & SWPPP Map")

# Prepare the data for the map
df = pd.DataFrame(data['swppp_compliance']['map_labels'])

view_state = pdk.ViewState(
    latitude=35.109028, longitude=-80.859390,
    zoom=17.5, pitch=45
)

# Pins Layer
points = pdk.Layer(
    "ScatterplotLayer", df,
    get_position="[lon, lat]",
    get_color="[230, 0, 0, 200]",
    get_radius=6,
)

# Label Layer
labels = pdk.Layer(
    "TextLayer", df,
    get_position="[lon, lat]",
    get_text="label",
    get_size=18,
    get_color=[255, 255, 255],
    get_alignment_baseline="'bottom'",
    get_pixel_offset=[0, -10],
)

st.pydeck_chart(pdk.Deck(
    map_style="mapbox://styles/mapbox/satellite-v9",
    api_keys={"mapbox": MAPBOX_TOKEN},
    initial_view_state=view_state,
    layers=[points, labels]
))
